


version: '2'
services:
  db:
    image: 'mariadb:10.2.12'
    container_name: 'lalucru_db'
    restart: unless-stopped
    volumes:
    - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=m3ta11Ic4
      - MYSQL_DATABASE=lalucru
      - MYSQL_USER=lalucru
      - MYSQL_PASSWORD=pik4c0in



  staging_app:
    image: thperret/timeoff-management:0.6.2
    container_name: 'staging_app'
    links:
      - db:db
    restart: unless-stopped
    volumes:
      - config:/opt/timeoff-management/config
    ports:
      - '3009:3000'
    environment:
      - ALLOW_ACCOUNTS_CREATION=false  
      - APP_URL=https://lamunca.eaudeweb.ro
      - NODE_ENV=production
      - MYSQL_HOST=db
      - MYSQL_DATABASE=lalucru
      - MYSQL_USER=lalucru
      - MYSQL_PASSWORD=pik4c0in




  app:
    image: thperret/timeoff-management:0.6.2
    container_name: 'lalucru_app'
    links:
      - db:db
    restart: unless-stopped
    volumes:
      - config:/opt/timeoff-management/config
    ports:
      - '3000:3000'
      - '8888:80'
    environment:
      - ALLOW_ACCOUNTS_CREATION=true  # set this to false to disable public account creation (set it once you have created your company to disable public regitration)
      - APP_URL=https://lalucru.eaudeweb.ro
      - NODE_ENV=production
      #- SENDER_MAIL=helpdesk@eaudeweb.ro
      #- SMTP_HOST=127.0.0.1
      #- SMTP_PORT=25
    # - SMTP_USER=
    # - SMTP_PASSWORD=
      - MYSQL_HOST=db
      - MYSQL_USER=lalucru
      - MYSQL_DATABASE=lalucru
      - MYSQL_PASSWORD=pik4c0in

volumes:
  db:
    driver: local
  config:
    driver: local
