db:
  image: 'mariadb:10.1.22'
  container_name: 'timeoff_db'
  restart: unless-stopped
  volumes:
    - ./volumes/db:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=timeoff
    - MYSQL_DATABASE=timeoff
    - MYSQL_USER=timeoff
    - MYSQL_PASSWORD=timeoff

app:
  image: thperret/timeoff-management:0.4.3
  container_name: 'timeoff_app'
  links:
    - db:db
  restart: unless-stopped
  volumes:
    - ./volumes/config:/opt/timeoff-management/config
  ports:
    - '3000:3000'
  environment:
    - ALLOW_ACCOUNTS_CREATION=true  # set this to false to disable public account creation (set it once you have created your company to disable public regitration)
    - APP_URL=https://timeoff.example.com
    - NODE_ENV=production
    # - SENDER_MAIL=timeoff@example.com # only set this if you want mail support
    # - SMTP_HOST=127.0.0.1
    # - SMTP_PORT=25
    # - SMTP_USER=timeoff
    # - SMTP_PASSWORD=timeoff
    - MYSQL_HOST=db
    - MYSQL_USER=timeoff
    - MYSQL_DATABASE=timeoff
    - MYSQL_PASSWORD=timeoff
